// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: account.proto

package account

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountClient interface {
	GetChartForCountry(ctx context.Context, in *CountryChartOption, opts ...grpc.CallOption) (*StringSlice, error)
	ValidateBankAccount(ctx context.Context, in *ValidateBankOption, opts ...grpc.CallOption) (*Bool, error)
	BuildTreeFromJson(ctx context.Context, in *BuildTreeOption, opts ...grpc.CallOption) (*AccountTreeList, error)
}

type accountClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountClient(cc grpc.ClientConnInterface) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) GetChartForCountry(ctx context.Context, in *CountryChartOption, opts ...grpc.CallOption) (*StringSlice, error) {
	out := new(StringSlice)
	err := c.cc.Invoke(ctx, "/account.account/GetChartForCountry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ValidateBankAccount(ctx context.Context, in *ValidateBankOption, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/account.account/ValidateBankAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) BuildTreeFromJson(ctx context.Context, in *BuildTreeOption, opts ...grpc.CallOption) (*AccountTreeList, error) {
	out := new(AccountTreeList)
	err := c.cc.Invoke(ctx, "/account.account/BuildTreeFromJson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
// All implementations must embed UnimplementedAccountServer
// for forward compatibility
type AccountServer interface {
	GetChartForCountry(context.Context, *CountryChartOption) (*StringSlice, error)
	ValidateBankAccount(context.Context, *ValidateBankOption) (*Bool, error)
	BuildTreeFromJson(context.Context, *BuildTreeOption) (*AccountTreeList, error)
	mustEmbedUnimplementedAccountServer()
}

// UnimplementedAccountServer must be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (UnimplementedAccountServer) GetChartForCountry(context.Context, *CountryChartOption) (*StringSlice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChartForCountry not implemented")
}
func (UnimplementedAccountServer) ValidateBankAccount(context.Context, *ValidateBankOption) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateBankAccount not implemented")
}
func (UnimplementedAccountServer) BuildTreeFromJson(context.Context, *BuildTreeOption) (*AccountTreeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildTreeFromJson not implemented")
}
func (UnimplementedAccountServer) mustEmbedUnimplementedAccountServer() {}

// UnsafeAccountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServer will
// result in compilation errors.
type UnsafeAccountServer interface {
	mustEmbedUnimplementedAccountServer()
}

func RegisterAccountServer(s grpc.ServiceRegistrar, srv AccountServer) {
	s.RegisterService(&Account_ServiceDesc, srv)
}

func _Account_GetChartForCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountryChartOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetChartForCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.account/GetChartForCountry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetChartForCountry(ctx, req.(*CountryChartOption))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_ValidateBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateBankOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ValidateBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.account/ValidateBankAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ValidateBankAccount(ctx, req.(*ValidateBankOption))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_BuildTreeFromJson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildTreeOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).BuildTreeFromJson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.account/BuildTreeFromJson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).BuildTreeFromJson(ctx, req.(*BuildTreeOption))
	}
	return interceptor(ctx, in, info, handler)
}

// Account_ServiceDesc is the grpc.ServiceDesc for Account service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Account_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChartForCountry",
			Handler:    _Account_GetChartForCountry_Handler,
		},
		{
			MethodName: "ValidateBankAccount",
			Handler:    _Account_ValidateBankAccount_Handler,
		},
		{
			MethodName: "BuildTreeFromJson",
			Handler:    _Account_BuildTreeFromJson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
