// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: hdArticle.proto

package hdArtcile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateArticleRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Idx        string `protobuf:"bytes,2,opt,name=Idx,proto3" json:"Idx,omitempty"`
	Views      int32  `protobuf:"varint,3,opt,name=Views,proto3" json:"Views,omitempty"`
	Helpful    int32  `protobuf:"varint,4,opt,name=Helpful,proto3" json:"Helpful,omitempty"`
	NotHelpful int32  `protobuf:"varint,5,opt,name=NotHelpful,proto3" json:"NotHelpful,omitempty"`
	HDArticle  string `protobuf:"bytes,6,opt,name=HDArticle,proto3" json:"HDArticle,omitempty"`
}

func (x *CreateArticleRecordRequest) Reset() {
	*x = CreateArticleRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdArticle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArticleRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRecordRequest) ProtoMessage() {}

func (x *CreateArticleRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hdArticle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRecordRequest) Descriptor() ([]byte, []int) {
	return file_hdArticle_proto_rawDescGZIP(), []int{0}
}

func (x *CreateArticleRecordRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRecordRequest) GetIdx() string {
	if x != nil {
		return x.Idx
	}
	return ""
}

func (x *CreateArticleRecordRequest) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *CreateArticleRecordRequest) GetHelpful() int32 {
	if x != nil {
		return x.Helpful
	}
	return 0
}

func (x *CreateArticleRecordRequest) GetNotHelpful() int32 {
	if x != nil {
		return x.NotHelpful
	}
	return 0
}

func (x *CreateArticleRecordRequest) GetHDArticle() string {
	if x != nil {
		return x.HDArticle
	}
	return ""
}

type CreateArticleRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CreateArticleRecordResponse) Reset() {
	*x = CreateArticleRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdArticle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArticleRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRecordResponse) ProtoMessage() {}

func (x *CreateArticleRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hdArticle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleRecordResponse) Descriptor() ([]byte, []int) {
	return file_hdArticle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleRecordResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdArticle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hdArticle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_hdArticle_proto_rawDescGZIP(), []int{2}
}

type CreateArticleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CreateArticleResponse) Reset() {
	*x = CreateArticleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdArticle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResponse) ProtoMessage() {}

func (x *CreateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hdArticle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return file_hdArticle_proto_rawDescGZIP(), []int{3}
}

func (x *CreateArticleResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IncrementViewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HdArticle string `protobuf:"bytes,1,opt,name=HdArticle,proto3" json:"HdArticle,omitempty"` // just name
	Idx       int32  `protobuf:"varint,2,opt,name=Idx,proto3" json:"Idx,omitempty"`
	Id        uint32 `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *IncrementViewRequest) Reset() {
	*x = IncrementViewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdArticle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementViewRequest) ProtoMessage() {}

func (x *IncrementViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hdArticle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementViewRequest.ProtoReflect.Descriptor instead.
func (*IncrementViewRequest) Descriptor() ([]byte, []int) {
	return file_hdArticle_proto_rawDescGZIP(), []int{4}
}

func (x *IncrementViewRequest) GetHdArticle() string {
	if x != nil {
		return x.HdArticle
	}
	return ""
}

func (x *IncrementViewRequest) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *IncrementViewRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IncrementViewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *IncrementViewResponse) Reset() {
	*x = IncrementViewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdArticle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementViewResponse) ProtoMessage() {}

func (x *IncrementViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hdArticle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementViewResponse.ProtoReflect.Descriptor instead.
func (*IncrementViewResponse) Descriptor() ([]byte, []int) {
	return file_hdArticle_proto_rawDescGZIP(), []int{5}
}

func (x *IncrementViewResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AddFeedbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HdArticle string `protobuf:"bytes,1,opt,name=HdArticle,proto3" json:"HdArticle,omitempty"` // just name
	Helpful   int32  `protobuf:"varint,2,opt,name=Helpful,proto3" json:"Helpful,omitempty"`
	Idx       int32  `protobuf:"varint,3,opt,name=Idx,proto3" json:"Idx,omitempty"`
	Id        uint32 `protobuf:"varint,4,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *AddFeedbackRequest) Reset() {
	*x = AddFeedbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdArticle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedbackRequest) ProtoMessage() {}

func (x *AddFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hdArticle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedbackRequest.ProtoReflect.Descriptor instead.
func (*AddFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_hdArticle_proto_rawDescGZIP(), []int{6}
}

func (x *AddFeedbackRequest) GetHdArticle() string {
	if x != nil {
		return x.HdArticle
	}
	return ""
}

func (x *AddFeedbackRequest) GetHelpful() int32 {
	if x != nil {
		return x.Helpful
	}
	return 0
}

func (x *AddFeedbackRequest) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *AddFeedbackRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddFeedbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Helpful    int32  `protobuf:"varint,2,opt,name=Helpful,proto3" json:"Helpful,omitempty"`
	NotHelpful int32  `protobuf:"varint,3,opt,name=NotHelpful,proto3" json:"NotHelpful,omitempty"`
	Content    string `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *AddFeedbackResponse) Reset() {
	*x = AddFeedbackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdArticle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedbackResponse) ProtoMessage() {}

func (x *AddFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hdArticle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedbackResponse.ProtoReflect.Descriptor instead.
func (*AddFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_hdArticle_proto_rawDescGZIP(), []int{7}
}

func (x *AddFeedbackResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddFeedbackResponse) GetHelpful() int32 {
	if x != nil {
		return x.Helpful
	}
	return 0
}

func (x *AddFeedbackResponse) GetNotHelpful() int32 {
	if x != nil {
		return x.NotHelpful
	}
	return 0
}

func (x *AddFeedbackResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_hdArticle_proto protoreflect.FileDescriptor

var file_hdArticle_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb2, 0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x64, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x49, 0x64, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x69, 0x65, 0x77,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x48, 0x65, 0x6c, 0x70, 0x66, 0x75, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x48, 0x65, 0x6c, 0x70, 0x66, 0x75, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x48,
	0x65, 0x6c, 0x70, 0x66, 0x75, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4e, 0x6f,
	0x74, 0x48, 0x65, 0x6c, 0x70, 0x66, 0x75, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x44, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x48, 0x44, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x22, 0x2f, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x29, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x56, 0x0a, 0x14, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x48, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x49, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x49,
	0x64, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x49, 0x64, 0x22, 0x29, 0x0a, 0x15, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x56,
	0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x6e, 0x0a,
	0x12, 0x41, 0x64, 0x64, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x48, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65, 0x6c, 0x70, 0x66, 0x75, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x48, 0x65, 0x6c, 0x70, 0x66, 0x75, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x49,
	0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x49, 0x64, 0x78, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x22, 0x7f, 0x0a,
	0x13, 0x41, 0x64, 0x64, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65,
	0x6c, 0x70, 0x66, 0x75, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x48, 0x65, 0x6c,
	0x70, 0x66, 0x75, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x48, 0x65, 0x6c, 0x70, 0x66,
	0x75, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4e, 0x6f, 0x74, 0x48, 0x65, 0x6c,
	0x70, 0x66, 0x75, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0xaf,
	0x02, 0x0a, 0x13, 0x54, 0x61, 0x62, 0x48, 0x44, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x46, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x13, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x65, 0x65, 0x64, 0x62,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x41, 0x64, 0x64,
	0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x56,
	0x69, 0x65, 0x77, 0x12, 0x15, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x56,
	0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x49, 0x6e, 0x63,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x15, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x1b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x68, 0x64, 0x41, 0x72, 0x74, 0x63, 0x69, 0x6c, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hdArticle_proto_rawDescOnce sync.Once
	file_hdArticle_proto_rawDescData = file_hdArticle_proto_rawDesc
)

func file_hdArticle_proto_rawDescGZIP() []byte {
	file_hdArticle_proto_rawDescOnce.Do(func() {
		file_hdArticle_proto_rawDescData = protoimpl.X.CompressGZIP(file_hdArticle_proto_rawDescData)
	})
	return file_hdArticle_proto_rawDescData
}

var file_hdArticle_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hdArticle_proto_goTypes = []interface{}{
	(*CreateArticleRecordRequest)(nil),  // 0: CreateArticleRecordRequest
	(*CreateArticleRecordResponse)(nil), // 1: CreateArticleRecordResponse
	(*CreateArticleRequest)(nil),        // 2: CreateArticleRequest
	(*CreateArticleResponse)(nil),       // 3: CreateArticleResponse
	(*IncrementViewRequest)(nil),        // 4: IncrementViewRequest
	(*IncrementViewResponse)(nil),       // 5: IncrementViewResponse
	(*AddFeedbackRequest)(nil),          // 6: AddFeedbackRequest
	(*AddFeedbackResponse)(nil),         // 7: AddFeedbackResponse
}
var file_hdArticle_proto_depIdxs = []int32{
	6, // 0: TabHDArticleService.AddFeedback:input_type -> AddFeedbackRequest
	4, // 1: TabHDArticleService.IncrementView:input_type -> IncrementViewRequest
	2, // 2: TabHDArticleService.CreateArticleObject:input_type -> CreateArticleRequest
	0, // 3: TabHDArticleService.CreateArticleRecord:input_type -> CreateArticleRecordRequest
	7, // 4: TabHDArticleService.AddFeedback:output_type -> AddFeedbackResponse
	5, // 5: TabHDArticleService.IncrementView:output_type -> IncrementViewResponse
	3, // 6: TabHDArticleService.CreateArticleObject:output_type -> CreateArticleResponse
	1, // 7: TabHDArticleService.CreateArticleRecord:output_type -> CreateArticleRecordResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hdArticle_proto_init() }
func file_hdArticle_proto_init() {
	if File_hdArticle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hdArticle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArticleRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdArticle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArticleRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdArticle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArticleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdArticle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArticleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdArticle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementViewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdArticle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementViewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdArticle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFeedbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdArticle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFeedbackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hdArticle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hdArticle_proto_goTypes,
		DependencyIndexes: file_hdArticle_proto_depIdxs,
		MessageInfos:      file_hdArticle_proto_msgTypes,
	}.Build()
	File_hdArticle_proto = out.File
	file_hdArticle_proto_rawDesc = nil
	file_hdArticle_proto_goTypes = nil
	file_hdArticle_proto_depIdxs = nil
}
