// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: hdTeam.proto

package hdTeam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTeamRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamName           string `protobuf:"bytes,1,opt,name=TeamName,proto3" json:"TeamName,omitempty"`
	IgnoreRestrictions bool   `protobuf:"varint,2,opt,name=IgnoreRestrictions,proto3" json:"IgnoreRestrictions,omitempty"`
	HDTeam             string `protobuf:"bytes,3,opt,name=HDTeam,proto3" json:"HDTeam,omitempty"`
}

func (x *CreateTeamRecordRequest) Reset() {
	*x = CreateTeamRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTeamRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRecordRequest) ProtoMessage() {}

func (x *CreateTeamRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRecordRequest) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTeamRecordRequest) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *CreateTeamRecordRequest) GetIgnoreRestrictions() bool {
	if x != nil {
		return x.IgnoreRestrictions
	}
	return false
}

func (x *CreateTeamRecordRequest) GetHDTeam() string {
	if x != nil {
		return x.HDTeam
	}
	return ""
}

type CreateTeamRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateTeamRecordResponse) Reset() {
	*x = CreateTeamRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTeamRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRecordResponse) ProtoMessage() {}

func (x *CreateTeamRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamRecordResponse) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTeamRecordResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{2}
}

type CreateTeamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTeamResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetAssignmentRuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAssignmentRuleRequest) Reset() {
	*x = GetAssignmentRuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssignmentRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentRuleRequest) ProtoMessage() {}

func (x *GetAssignmentRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentRuleRequest.ProtoReflect.Descriptor instead.
func (*GetAssignmentRuleRequest) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{4}
}

type GetAssignmentRuleResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignmentRuleResponse []*GetAssignmentRuleResponse `protobuf:"bytes,1,rep,name=AssignmentRuleResponse,proto3" json:"AssignmentRuleResponse,omitempty"`
}

func (x *GetAssignmentRuleResponses) Reset() {
	*x = GetAssignmentRuleResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssignmentRuleResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentRuleResponses) ProtoMessage() {}

func (x *GetAssignmentRuleResponses) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentRuleResponses.ProtoReflect.Descriptor instead.
func (*GetAssignmentRuleResponses) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{5}
}

func (x *GetAssignmentRuleResponses) GetAssignmentRuleResponse() []*GetAssignmentRuleResponse {
	if x != nil {
		return x.AssignmentRuleResponse
	}
	return nil
}

type GetAssignmentRuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DocumentType string `protobuf:"bytes,2,opt,name=DocumentType,proto3" json:"DocumentType,omitempty"`
}

func (x *GetAssignmentRuleResponse) Reset() {
	*x = GetAssignmentRuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssignmentRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentRuleResponse) ProtoMessage() {}

func (x *GetAssignmentRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentRuleResponse.ProtoReflect.Descriptor instead.
func (*GetAssignmentRuleResponse) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssignmentRuleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAssignmentRuleResponse) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

type CreateAssignmentRuleDayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAssignmentRuleDayRequest) Reset() {
	*x = CreateAssignmentRuleDayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAssignmentRuleDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssignmentRuleDayRequest) ProtoMessage() {}

func (x *CreateAssignmentRuleDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssignmentRuleDayRequest.ProtoReflect.Descriptor instead.
func (*CreateAssignmentRuleDayRequest) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{7}
}

type CreateAssignmentRuleDayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAssignmentRuleDayResponse) Reset() {
	*x = CreateAssignmentRuleDayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAssignmentRuleDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssignmentRuleDayResponse) ProtoMessage() {}

func (x *CreateAssignmentRuleDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssignmentRuleDayResponse.ProtoReflect.Descriptor instead.
func (*CreateAssignmentRuleDayResponse) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{8}
}

type CreateAssignmentRuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *CreateAssignmentRuleRequest) Reset() {
	*x = CreateAssignmentRuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAssignmentRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssignmentRuleRequest) ProtoMessage() {}

func (x *CreateAssignmentRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssignmentRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateAssignmentRuleRequest) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAssignmentRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateAssignmentRuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DocumentType string `protobuf:"bytes,2,opt,name=DocumentType,proto3" json:"DocumentType,omitempty"`
}

func (x *CreateAssignmentRuleResponse) Reset() {
	*x = CreateAssignmentRuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdTeam_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAssignmentRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssignmentRuleResponse) ProtoMessage() {}

func (x *CreateAssignmentRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hdTeam_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssignmentRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateAssignmentRuleResponse) Descriptor() ([]byte, []int) {
	return file_hdTeam_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAssignmentRuleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAssignmentRuleResponse) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

var File_hdTeam_proto protoreflect.FileDescriptor

var file_hdTeam_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x68, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d,
	0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65, 0x61,
	0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x65, 0x61,
	0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x12, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x44, 0x54, 0x65, 0x61, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x48, 0x44, 0x54, 0x65, 0x61, 0x6d, 0x22, 0x2c, 0x0a,
	0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x13, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x26, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x70, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x73, 0x12, 0x52, 0x0a, 0x16, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x16,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x53, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x20, 0x0a, 0x1e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x75, 0x6c, 0x65, 0x44, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x21, 0x0a,
	0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x75, 0x6c, 0x65, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x31, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x56, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x32, 0xc3, 0x02, 0x0a, 0x10,
	0x54, 0x61, 0x62, 0x48, 0x44, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x55, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x19, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x65, 0x61, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x68, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hdTeam_proto_rawDescOnce sync.Once
	file_hdTeam_proto_rawDescData = file_hdTeam_proto_rawDesc
)

func file_hdTeam_proto_rawDescGZIP() []byte {
	file_hdTeam_proto_rawDescOnce.Do(func() {
		file_hdTeam_proto_rawDescData = protoimpl.X.CompressGZIP(file_hdTeam_proto_rawDescData)
	})
	return file_hdTeam_proto_rawDescData
}

var file_hdTeam_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_hdTeam_proto_goTypes = []interface{}{
	(*CreateTeamRecordRequest)(nil),         // 0: CreateTeamRecordRequest
	(*CreateTeamRecordResponse)(nil),        // 1: CreateTeamRecordResponse
	(*CreateTeamRequest)(nil),               // 2: CreateTeamRequest
	(*CreateTeamResponse)(nil),              // 3: CreateTeamResponse
	(*GetAssignmentRuleRequest)(nil),        // 4: GetAssignmentRuleRequest
	(*GetAssignmentRuleResponses)(nil),      // 5: GetAssignmentRuleResponses
	(*GetAssignmentRuleResponse)(nil),       // 6: GetAssignmentRuleResponse
	(*CreateAssignmentRuleDayRequest)(nil),  // 7: CreateAssignmentRuleDayRequest
	(*CreateAssignmentRuleDayResponse)(nil), // 8: CreateAssignmentRuleDayResponse
	(*CreateAssignmentRuleRequest)(nil),     // 9: CreateAssignmentRuleRequest
	(*CreateAssignmentRuleResponse)(nil),    // 10: CreateAssignmentRuleResponse
}
var file_hdTeam_proto_depIdxs = []int32{
	6,  // 0: GetAssignmentRuleResponses.AssignmentRuleResponse:type_name -> GetAssignmentRuleResponse
	9,  // 1: TabHDTeamService.CreateAssignmentRule:input_type -> CreateAssignmentRuleRequest
	4,  // 2: TabHDTeamService.GetAssignmentRules:input_type -> GetAssignmentRuleRequest
	2,  // 3: TabHDTeamService.CreateTeamObject:input_type -> CreateTeamRequest
	0,  // 4: TabHDTeamService.CreateTeamRecord:input_type -> CreateTeamRecordRequest
	10, // 5: TabHDTeamService.CreateAssignmentRule:output_type -> CreateAssignmentRuleResponse
	5,  // 6: TabHDTeamService.GetAssignmentRules:output_type -> GetAssignmentRuleResponses
	3,  // 7: TabHDTeamService.CreateTeamObject:output_type -> CreateTeamResponse
	1,  // 8: TabHDTeamService.CreateTeamRecord:output_type -> CreateTeamRecordResponse
	5,  // [5:9] is the sub-list for method output_type
	1,  // [1:5] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_hdTeam_proto_init() }
func file_hdTeam_proto_init() {
	if File_hdTeam_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hdTeam_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTeamRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdTeam_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTeamRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdTeam_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdTeam_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTeamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdTeam_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssignmentRuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdTeam_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssignmentRuleResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdTeam_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssignmentRuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdTeam_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAssignmentRuleDayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdTeam_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAssignmentRuleDayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdTeam_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAssignmentRuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdTeam_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAssignmentRuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hdTeam_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hdTeam_proto_goTypes,
		DependencyIndexes: file_hdTeam_proto_depIdxs,
		MessageInfos:      file_hdTeam_proto_msgTypes,
	}.Build()
	File_hdTeam_proto = out.File
	file_hdTeam_proto_rawDesc = nil
	file_hdTeam_proto_goTypes = nil
	file_hdTeam_proto_depIdxs = nil
}
